name: Build Plugin Dev Release

on:
  push:
    branches:
      - "develop"
      - "vaccfr"

env:
  DLL_NAME: vACDM.dll
  BUILD_CONFIGURATION: Release
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSION: "0"
  DEV_RELEASE: "1"

jobs:
  formatting-check:
    uses: ./.github/workflows/clang-format.yml

  build:
    needs: formatting-check
    runs-on: windows-latest
    name: "Build plugin"

    steps:
      - uses: actions/checkout@v4

      - name: Checkout submodules
        shell: bash
        run: git submodule update --init --recursive vcpkg

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run version handler
        env:
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
        run: |
          python .github/workflows/version_handler.py

      - name: Determine DEV_RELEASE value
        id: find_latest_dev_release
        env:
          REPOSITORY: ${{ github.repository }}
        run: python .github/workflows/determine_dev_release.py

      - name: Install MSVC toolset
        run: choco upgrade visualstudio2022buildtools

      - name: Set up MSVC environment
        shell: pwsh
        run: |
          Import-Module "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell -VsInstallPath "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_CONFIGURATION}} -A Win32 -DDEV_BUILD=ON -DDEV_RELEASE_NUMBER="${{ env.DEV_RELEASE }}"

      - name: Build DLL
        run: cmake --build build --config ${{env.BUILD_CONFIGURATION}}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          draft: true
          prerelease: true
          generate_release_notes: true
          files: |
            build/${{env.BUILD_CONFIGURATION}}/${{env.DLL_NAME}}
            src/config/vacdm.txt
